version: '3.7'

services:
  backend:
    build: ./backend
    command: python main.py
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://todo_db_username:todo_db_password@todo_db/todo_db_dev

  todo_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_todo:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todo_db_username
      - POSTGRES_PASSWORD=todo_db_password
      - POSTGRES_DB=todo_db_dev

  frontend:
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend/:/frontend/
    ports:
      - 3000:3080
    
  nginx:
    image: nginx:latest
    ports: 
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data_todo: