FROM python:3.8-slim

WORKDIR /backend

COPY ./requirements.txt /backend/requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /backend/requirements.txt \
    && rm -rf /root/.cache/pip

COPY . /backend/